development:
  adapter: postgresql
  database: my_database_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: my_datbase_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: my_datbase_production
  encoding: unicode 
  pool: 5
  timeout: 5000
